### ISSUE TITLE
transform crashes when git is in folder

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#139]
[root@docs-qa /www/mie-docs]# node /root/wikiGDrive/src/cli.ts transform
✔ Wikigdrive initialized
✔ Transforming 0/0
⠹ Quota: 95 queries / 10 seconds
TypeError: Cannot read property 'findFiles' of undefined
    at GitPlugin.<anonymous> (/root/wikiGDrive/src/plugins/GitPlugin.ts:79:48)
    at Generator.next (<anonymous>)
    at fulfilled (/root/wikiGDrive/src/plugins/GitPlugin.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by horner** [comment]
Duplicate of #148
