### ISSUE TITLE
Check git lfs

### ISSUE THREAD

**Issue by ggodlewski** [mieweb/wikiGDrive#333]
Change to use simple-git for reset, clean, operations. too.

<img width="1356" alt="Screenshot 2022-10-29 at 10 24 28 AM" src="https://user-images.githubusercontent.com/6094599/198845216-aab64342-cf52-49bb-a8da-fc31730c4f1b.png">

**Comment by horner** [comment]
Reset to remote failed:

```
[2022-10-29T16:01:08.772Z] [GitScanner.ts](https://github.com/mieweb/wikiGDrive/blob/develop/src/git/GitScanner.ts#L286) git reset on remote: git@github.com:mieweb/docs.git#master
[2022-10-29T16:01:08.774Z] [GitScanner.ts](https://github.com/mieweb/wikiGDrive/blob/develop/src/git/GitScanner.ts#L290) git fetch origin
[2022-10-29T16:01:08.830Z] [GitController.ts](https://github.com/mieweb/wikiGDrive/blob/develop/src/containers/server/routes/GitController.ts#L133) Error: failed to start SSH session: Unable to ask for ssh-userauth service
    at async Object.resetRemote (file:///usr/src/app/src/containers/server/routes/GitController.ts:127:7)
    at async file:///usr/src/app/src/containers/server/routes/Controller.ts:255:26
[2022-10-29T16:01:26.704Z] [GitScanner.ts](https://github.com/mieweb/wikiGDrive/blob/develop/src/git/GitScanner.ts#L286) git reset on remote: git@github.com:mieweb/docs.git#master
[2022-10-29T16:01:26.705Z] [GitScanner.ts](https://github.com/mieweb/wikiGDrive/blob/develop/src/git/GitScanner.ts#L290) git fetch origin
```

**Comment by monpie3** [comment]
Confirmed with Greg is already working and can be closed.
