### ISSUE TITLE
(src/containers/google_folder/GoogleFolderContainer.ts): Error: Internal Error

### ISSUE THREAD

**Issue by wreiske** [mieweb/wikiGDrive#400]
```
2023-11-16T17:51:58.369Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1kK4-VsEd_9DgH2j0H5pW-TwjwAqXTQ7gg84IjhMMszw.odt [Task Search]
2023-11-16T17:51:59.971Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1HPEy9sWojSVb5ebfsWoQ0io8hjQ7fDFZGlfi0T6xT1k.odt [Task List]
2023-11-16T17:52:00.143Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1n6mexq2OOHyGdWBYutejlrZ6IXupdbAGReupGd28Kag.odt [Adding Tasks]
2023-11-16T17:52:01.681Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1AaUA4udtUH_f1fqh8lEkGP4Zssm4tYIAr0DwY4EcZnU.odt [Incoming File/Fax Q Set-Up and Documentation]
2023-11-16T17:52:03.466Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1iUHC57VH5eIkqBnQz1sPngMkcFR9V4ZD0bbdhTT8ETk.odt [Fax Manager Tab - Outbound Faxing]
2023-11-16T17:52:08.279Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1m6v3HgyiGVoT4r2LTce3OC0uSMx00sczOS4Pu10rU-g.odt [Faxing Documents]
2023-11-16T17:52:09.664Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 184cEFR0ZGXqOKRMfcjRH0NFDEQg5mJ9SWlnOiPPOnUs.odt [Injection Editor]
2023-11-16T17:52:09.909Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1cVM6kOokD8qoZ7i7IdJY4lVB2RIXhgOoDG1fNBPY5kQ.odt [Injection Tab with CHIRP Interface]
2023-11-16T17:52:10.381Z [error] (src/containers/google_folder/GoogleFolderContainer.ts): Error: Internal Error
    at convertResponseToError (file:///usr/src/app/src/google/driveFetch.ts:123:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.job [as func] (file:///usr/src/app/src/google/driveFetch.ts:175:25)
    at async file:///usr/src/app/src/google/QuotaLimiter.ts:169:13
2023-11-16T17:52:10.383Z [error] (src/containers/google_folder/QueueDownloader.ts): Error: Internal Error
    at convertResponseToError (file:///usr/src/app/src/google/driveFetch.ts:123:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.job [as func] (file:///usr/src/app/src/google/driveFetch.ts:175:25)
    at async file:///usr/src/app/src/google/QuotaLimiter.ts:169:13
2023-11-16T17:52:10.534Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1M8Bx-VKTH5JvE4T3NhdDD5UtC57klrxTeRBelJGhy0k.odt [Outbound Faxing Email Notifications of Sent/Failed Faxes]
2023-11-16T17:52:18.203Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1uPwVGcsvmIAnKx3-a0wKVekf6dHuls2_mbR8WE7_zD8.odt [Unknown Allergy/Medication Email Notifications]
2023-11-16T17:52:18.992Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1oP6Hhh_LPanOBoETFuY4S6cL8QxKmuwL_LHThe-QWpI.odt [Edit/Delete Injections/Immunizations]
2023-11-16T17:52:19.879Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 11_gJvEXt_A9TeALtLbhxsUzWimA0i3C3qi0TZ1w43dk.odt [Injection Tab - Vials]
2023-11-16T17:52:20.087Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1O4s5YPHkNa_EGcmZ9rlsWai2yIrqQnQrEnQHLnTigTk.odt [Injection Tab]
2023-11-16T17:52:24.254Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1gaHfjLq39wqQJRPf8fH6ozhs4LyAdTUxiG2JeKq0lPI.odt [Prescribing/Adding Medications]
2023-11-16T17:52:27.980Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1k3Awk1LcoMrM84yIqC3rGUiGe9LqXWOLAEaBz2vFSAE.odt [Drug Plan and Formularies]
2023-11-16T17:52:28.341Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1ZhUOL7iD9PJzjgUtbgqs-P-OOiRL5JMLHIfOXC5yLtE.odt [E-Refills - All E-Refills Tab]
```

a few moments later.....

```
2023-11-16T17:57:49.524Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1zw0h2f_SwtwbsqdafoMi75CjleDcVn4vHV9_XZ7bW_8.odt [System Anatomy]
2023-11-16T17:57:49.550Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1l64IjN7y0I0QHoM7e8hyy80El5GBEv4DC_WN8zFGt1Q.odt [What You Need to Know]
2023-11-16T17:57:49.608Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1mzFSt5w-9M3rZjHAehLuli0zz3d_eVNp1V2k4QLZbyk.odt [End-of-Year Is Here: Keeping Up with CMS]
2023-11-16T17:57:57.033Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1SHajJrhtwYmjKyAS3M1-3NTKOCI4liepuWkNbor1vN0.odt [Electronic Health Information (EHI) Export]
2023-11-16T17:57:57.136Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Listening: 1_4OSCeFgFNIS42EVWlp0h-mIAb3XzKdx
2023-11-16T17:57:57.314Z [error] (src/containers/google_folder/GoogleFolderContainer.ts): TypeError: terminated
    at Fetch.onAborted (node:internal/deps/undici/undici:9975:53)
    at Fetch.emit (node:events:517:28)
    at Fetch.emit (node:domain:489:12)
    at Fetch.terminate (node:internal/deps/undici/undici:9174:14)
    at Object.onError (node:internal/deps/undici/undici:10092:38)
    at _Request.onError (node:internal/deps/undici/undici:6344:31)
    at errorRequest (node:internal/deps/undici/undici:8852:17)
    at TLSSocket.onSocketClose (node:internal/deps/undici/undici:8021:9)
    at TLSSocket.emit (node:events:529:35)
    at TLSSocket.emit (node:domain:489:12)
2023-11-16T17:57:57.316Z [error] (src/containers/google_folder/QueueDownloader.ts): TypeError: terminated
    at Fetch.onAborted (node:internal/deps/undici/undici:9975:53)
    at Fetch.emit (node:events:517:28)
    at Fetch.emit (node:domain:489:12)
    at Fetch.terminate (node:internal/deps/undici/undici:9174:14)
    at Object.onError (node:internal/deps/undici/undici:10092:38)
    at _Request.onError (node:internal/deps/undici/undici:6344:31)
    at errorRequest (node:internal/deps/undici/undici:8852:17)
    at TLSSocket.onSocketClose (node:internal/deps/undici/undici:8021:9)
    at TLSSocket.emit (node:events:529:35)
    at TLSSocket.emit (node:domain:489:12)
2023-11-16T17:57:57.586Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1iN5EvKl23ZMf2h8fIgSUDxhRrSR7ChMCCJHa6zqOxMI.odt [MIPS: Pick Your Pace]
2023-11-16T17:57:59.386Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 12p7Iy880e45Q2ET2g2wDFFRzSW5kUkrwhO8Y77UhkfQ.odt [MACRA: Quality Payment Program (QPP)]
2023-11-16T17:58:01.149Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1dpBE40WHHZcXc2vs9jWtBsoHS-4NiCZPKXLbmG8-HX4.odt [Interface Specifications]
2023-11-16T17:58:01.548Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1Uk4ZHLX68xzYUxKdfF2RyJm2wURwuTz18RhBo71CgLA.odt [CCDA, CCD and CCR Compatibility]
2023-11-16T17:58:01.652Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Listening: 1uWsxZgKQn5wnb5Wa81Y4xDUvFsa02rBf
2023-11-16T17:58:01.708Z [info] (src/containers/google_folder/GoogleFolderContainer.ts): Exported document: 1buEjhEqeF7YkD4D8XltrDAHKHNbfICRz9wGqUqMz2ks.odt [Application Programming Interface (API)]
```

**Comment by ggodlewski** [comment]
Unable to reproduce
