### ISSUE TITLE
Error: Error watching changes

### ISSUE THREAD

**Issue by wreiske** [mieweb/wikiGDrive#96]
@ggodlewski it looks like https://github.com/mieweb/wikiGDrive/pull/95 did not actually fix the issue.

```
Error: Error watching changes
    at new t (/root/wikiGDrive/dist/main.js:2:86022)
    at e.<anonymous> (/root/wikiGDrive/dist/main.js:2:89622)
    at /root/wikiGDrive/dist/main.js:2:85570
    at Object.throw (/root/wikiGDrive/dist/main.js:2:85675)
    at c (/root/wikiGDrive/dist/main.js:2:84440) {
  origError: Error: Missing required parameters: pageToken
      at f (/root/wikiGDrive/dist/main.js:3:90347)
      at Object.t.createAPIRequest (/root/wikiGDrive/dist/main.js:3:92700)
      at o.list (/root/wikiGDrive/dist/main.js:3:2872428)
      at e.<anonymous> (/root/wikiGDrive/dist/main.js:2:89257)
      at /root/wikiGDrive/dist/main.js:2:85570
      at Object.next (/root/wikiGDrive/dist/main.js:2:85675)
      at /root/wikiGDrive/dist/main.js:2:84587
      at new Promise (<anonymous>)
      at a (/root/wikiGDrive/dist/main.js:2:84332)
      at e.watchChanges (/root/wikiGDrive/dist/main.js:2:88830),
  isQuotaError: undefined,
  file: undefined,
  dest: undefined,
  folderId: undefined
}
```

**Comment by wreiske** [comment]
https://developers.google.com/drive/api/v3/manage-changes
